channels:
  - conda-forge
  - rdkit
  - pytorch
dependencies:
  - python=3.7.4
  - rdkit
  - numpy
  - pytest
  - pytest-mock
  - matplotlib
  - tqdm
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - ipywidgets
  - h5py