acc_batches: 4
activation: gelu
aug_prob: 0.5
augment: all
batch_size: 128
clip_grad: 1.0
d_feedforward: 2048
d_model: 512
dropout: 0.1
epochs: 500
limit_val_batches: 1.0
lr: 0.001
mask_prob: 0.1
max_seq_len: 512
num_buckets: 24
num_heads: 8
num_layers: 6
num_steps: 39501
pad_token_idx: 0
schedule: cycle
task: mask_aug
train_tokens: None
vocab_size: 523
warm_up_steps: 8000
weight_decay: 0.0
